### ISSUE TITLE
Low code coverage

### ISSUE THREAD

**Issue by mianasbat** [SciKit-Surgery/scikit-surgerynditracker#31]
The coverage status on repo home page shows 59%.

**Comment by thompson318** [comment]
Coverage is low because a lot of the tests can't be done without the tracking hardware. This could be addressed by building some sort of simulated tracker that we could connect to, which might be fun but would be quite a lot of work.

**Comment by thompson318** [comment]
@mxochicale , this issue is better now (coverage up to 85%) but maybe could be better. Have a look after you've done first tutorial.

**Comment by thompson318** [comment]
That's an odd error. This test is meant to check that the command ndiDeviceName(port_number) returns the same name as list_ports.comports(). We added it after #37 . Presumably this is the log from your local (ubuntu) machine?

**Comment by mxochicale** [comment]
Indeed, the log is from local machine with Ubuntu 22.10 LTS (Kinetic Kudu).  I see that current ci.yml is working fine with "ubuntu-18.04" python-ver: [3.7, 3.8], so will try "runs-on: ubuntu-22.04" in the workflow file to see the output. 

will try to dig in a bit more on " assert '/dev/ttyS4' in ['/dev/ttyS0']" and any pointers/thoughts are welcome. 

> FYI. GitHub Actions: The Ubuntu 18.04 Actions runner image is being deprecated and will be removed by 12/1/22 
https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/

**Comment by mxochicale** [comment]
Tests are fine for Ubuntu 20.04.5 with python 3.7, 3.8 3.9: https://github.com/SciKit-Surgery/scikit-surgerynditracker/actions/runs/3328217356 


*  test (ubuntu-latest, 3.7) succeeded 14 minutes ago in 46s  
```
 Current runner version: '2.298.2'
Operating System
  Ubuntu
  20.04.5
  LTS
Runner Image
  Image: ubuntu-20.04
  Version: 20221018.2
  Included Software: https://github.com/actions/runner-images/blob/ubuntu20/20221018.2/images/linux/Ubuntu2004-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20221018.2


...


 ============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-7.2.0, pluggy-1.0.0 -- /opt/hostedtoolcache/Python/3.7.15/x64/bin/python
cachedir: .pytest_cache
rootdir: /home/runner/work/scikit-surgerynditracker/scikit-surgerynditracker
plugins: mock-3.10.0, pyfakefs-5.0.0
collecting ... collected 15 items

tests/test_listports.py::test_list_ports ['/dev/ttyS1', '/dev/ttyS0']
Checking port: /dev/ttyS1 ['/dev/ttyS0', '/dev/ttyS1']
Checking port: /dev/ttyS0 ['/dev/ttyS0', '/dev/ttyS1']
PASSED
tests/test_requirements.py::test_requirements_vs_setup PASSED
tests/test_sksurgerynditracker.py::test_connect PASSED
tests/test_sksurgerynditracker.py::test_connect_quaternions PASSED
ping: 999.999.999.999: Name or service not known
tests/test_sksurgerynditracker.py::test_connect_network PASSED
tests/test_sksurgerynditracker.py::test_connect_serial PASSED
tests/test_sksurgerynditracker.py::test_configure Probing port:  0  got name:  /dev/ttyS1  Result:  257
Probing port:  1  got name:  /dev/ttyS0  Result:  257
Probing port:  COM2  Result:  257

```


*  test (ubuntu-latest, 3.8) succeeded 15 minutes ago in 52s 

```



Operating System
  Ubuntu
  20.04.5
  LTS
Runner Image
  Image: ubuntu-20.04
  Version: 20221024.1
  Included Software: https://github.com/actions/runner-images/blob/ubuntu20/20221024.1/images/linux/Ubuntu2004-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20221024.1


...


 ============================= test session starts ==============================
platform linux -- Python 3.8.14, pytest-7.2.0, pluggy-1.0.0 -- /opt/hostedtoolcache/Python/3.8.14/x64/bin/python
cachedir: .pytest_cache
rootdir: /home/runner/work/scikit-surgerynditracker/scikit-surgerynditracker
plugins: mock-3.10.0, pyfakefs-5.0.0
collecting ... collected 15 items

tests/test_listports.py::test_list_ports ['/dev/ttyS1', '/dev/ttyS0']
Checking port: /dev/ttyS1 ['/dev/ttyS0', '/dev/ttyS1']
Checking port: /dev/ttyS0 ['/dev/ttyS0', '/dev/ttyS1']
PASSED
tests/test_requirements.py::test_requirements_vs_setup PASSED
tests/test_sksurgerynditracker.py::test_connect PASSED
tests/test_sksurgerynditracker.py::test_connect_quaternions PASSED
ping: 999.999.999.999: Name or service not known
tests/test_sksurgerynditracker.py::test_connect_network PASSED
tests/test_sksurgerynditracker.py::test_connect_serial PASSED
tests/test_sksurgerynditracker.py::test_configure Probing port:  0  got name:  /dev/ttyS1  Result:  257
Probing port:  1  got name:  /dev/ttyS0  Result:  257
Probing port:  COM2  Result:  257


```

*  test (ubuntu-latest, 3.9) succeeded 15 minutes ago in 31s 
```


Operating System
  Ubuntu
  20.04.5
  LTS
Runner Image
  Image: ubuntu-20.04
  Version: 20221018.2
  Included Software: https://github.com/actions/runner-images/blob/ubuntu20/20221018.2/images/linux/Ubuntu2004-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20221018.2


...


 ============================= test session starts ==============================
platform linux -- Python 3.9.15, pytest-7.2.0, pluggy-1.0.0 -- /opt/hostedtoolcache/Python/3.9.15/x64/bin/python
cachedir: .pytest_cache
rootdir: /home/runner/work/scikit-surgerynditracker/scikit-surgerynditracker
plugins: mock-3.10.0, pyfakefs-5.0.0
collecting ... collected 15 items

tests/test_listports.py::test_list_ports ['/dev/ttyS1', '/dev/ttyS0']
Checking port: /dev/ttyS1 ['/dev/ttyS0', '/dev/ttyS1']
Checking port: /dev/ttyS0 ['/dev/ttyS0', '/dev/ttyS1']
PASSED
tests/test_requirements.py::test_requirements_vs_setup PASSED
tests/test_sksurgerynditracker.py::test_connect PASSED
tests/test_sksurgerynditracker.py::test_connect_quaternions PASSED
ping: 999.999.999.999: Name or service not known
tests/test_sksurgerynditracker.py::test_connect_network PASSED
tests/test_sksurgerynditracker.py::test_connect_serial PASSED
tests/test_sksurgerynditracker.py::test_configure Probing port:  0  got name:  /dev/ttyS1  Result:  257
Probing port:  1  got name:  /dev/ttyS0  Result:  257
Probing port:  COM2  Result:  257
```

**Comment by mxochicale** [comment]
Tried the following in Ubuntu22.10,

```
sudo apt install setserial
setserial -g /dev/ttyS[0123456789]
/dev/ttyS0: Permission denied
/dev/ttyS1: Permission denied
/dev/ttyS2: Permission denied
/dev/ttyS3: Permission denied
/dev/ttyS4: Permission denied
/dev/ttyS5: Permission denied
/dev/ttyS6: Permission denied
/dev/ttyS7: Permission denied
/dev/ttyS8: Permission denied
/dev/ttyS9: Permission denied
````
```
sudo adduser mxochicale dialout
```
REBOOT

```
setserial -g /dev/ttyS[0123456789]
/dev/ttyS0, UART: unknown, Port: 0x03f8, IRQ: 4
/dev/ttyS1, UART: unknown, Port: 0x02f8, IRQ: 3
/dev/ttyS2, UART: unknown, Port: 0x03e8, IRQ: 4
/dev/ttyS3, UART: unknown, Port: 0x02e8, IRQ: 3
/dev/ttyS4, UART: 16550A, Port: 0x4060, IRQ: 19
/dev/ttyS5, UART: unknown, Port: 0x0000, IRQ: 0
/dev/ttyS6, UART: unknown, Port: 0x0000, IRQ: 0
/dev/ttyS7, UART: unknown, Port: 0x0000, IRQ: 0
/dev/ttyS8, UART: unknown, Port: 0x0000, IRQ: 0
/dev/ttyS9, UART: unknown, Port: 0x0000, IRQ: 0
```

However, it seems to be an open problem https://askubuntu.com/questions/1063037/addressing-of-com-ports-on-ubuntu-dont-match-labels. 

Perhaps I will use [Ubuntu 22.04.1 LTS ](https://wiki.ubuntu.com/Releases) as Ubuntu22.10 (which is not LTS) and not supported in the github actions.

**Comment by mxochicale** [comment]
Interesting, just reinstalled OS Ubuntu 22.04.1 LTS and all dependencies but got same problem: 

```
(scikit-surgerynditrackerVE) mxochicale@precision-5570:~/repositories/SciKit-Surgery/scikit-surgerynditracker$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS

```

```
tests/test_listports.py::test_list_ports List of available ports:  ['/dev/ttyS4']
Checking port: /dev/ttyS4 in ndi_port_names:  ['/dev/ttyS0']
FAILED


        for serial_port in serial_ports:
            pyserial_port_name = serial_port.device
            print("Checking port:", pyserial_port_name,
                  "in ndi_port_names: ", ndi_port_names)
>           assert pyserial_port_name in ndi_port_names
E           AssertionError: assert '/dev/ttyS4' in ['/dev/ttyS0']

tests/test_listports.py:37: AssertionError
============================================================================================= short test summary info =============================================================================================
FAILED tests/test_listports.py::test_list_ports - AssertionError: assert '/dev/ttyS4' in ['/dev/ttyS0']
========================================================================================== 1 failed, 14 passed in 0.27s ===========================================================================================
ERROR: InvocationError for command /home/mxochicale/repositories/SciKit-Surgery/scikit-surgerynditracker/.tox/py37/bin/coverage run -a --source ./sksurgerynditracker -m pytest -s -v (exited with code 1)
lint create: /home/mxochicale/repositories/SciKit-Surgery/scikit-surgerynditracker/.tox/lint


```

**Comment by mxochicale** [comment]
Last commit for `/sksurgerynditracker/nditracker.py` reached a coverage of **92.308%** where the following points remain to be covered:

*  **firmware values for ' AURORA Rev 007', ' AURORA Rev 008', ' Polaris Vega 008', ' Polaris Spectra Rev 006' which don't hit:** 

https://github.com/SciKit-Surgery/scikit-surgerynditracker/blob/888af08e29acbed44219729b87ee06cb4809bb01/sksurgerynditracker/nditracker.py#L163-L165

* **Close device for vega tracker type: `  if self._tracker_type == "vega":`** 

https://github.com/SciKit-Surgery/scikit-surgerynditracker/blob/888af08e29acbed44219729b87ee06cb4809bb01/sksurgerynditracker/nditracker.py#L313

* **Using ` _read_sroms_from_file(self):` for aurora tracker type:**

https://github.com/SciKit-Surgery/scikit-surgerynditracker/blob/888af08e29acbed44219729b87ee06cb4809bb01/sksurgerynditracker/nditracker.py#L341

* **Using ` get_frame(self):` for not dummy devices:**

https://github.com/SciKit-Surgery/scikit-surgerynditracker/blob/888af08e29acbed44219729b87ee06cb4809bb01/sksurgerynditracker/nditracker.py#L450-L454

https://github.com/SciKit-Surgery/scikit-surgerynditracker/blob/888af08e29acbed44219729b87ee06cb4809bb01/sksurgerynditracker/nditracker.py#L457

https://github.com/SciKit-Surgery/scikit-surgerynditracker/blob/888af08e29acbed44219729b87ee06cb4809bb01/sksurgerynditracker/nditracker.py#L460-L463

https://github.com/SciKit-Surgery/scikit-surgerynditracker/blob/888af08e29acbed44219729b87ee06cb4809bb01/sksurgerynditracker/nditracker.py#L467

https://github.com/SciKit-Surgery/scikit-surgerynditracker/blob/888af08e29acbed44219729b87ee06cb4809bb01/sksurgerynditracker/nditracker.py#L467

https://github.com/SciKit-Surgery/scikit-surgerynditracker/blob/888af08e29acbed44219729b87ee06cb4809bb01/sksurgerynditracker/nditracker.py#L469-L471

https://github.com/SciKit-Surgery/scikit-surgerynditracker/blob/888af08e29acbed44219729b87ee06cb4809bb01/sksurgerynditracker/nditracker.py#L460-L463

https://github.com/SciKit-Surgery/scikit-surgerynditracker/blob/888af08e29acbed44219729b87ee06cb4809bb01/sksurgerynditracker/nditracker.py#L473 

https://github.com/SciKit-Surgery/scikit-surgerynditracker/blob/888af08e29acbed44219729b87ee06cb4809bb01/sksurgerynditracker/nditracker.py#L475

**Comment by thompson318** [comment]
Coverage is now around 98%. Closing this issue.
