### ISSUE TITLE
pip install fails [Errno 2] No such file or directory: 'README.pypi.md'

### ISSUE THREAD

**Issue by Mixmorks** [SciKit-Surgery/scikit-surgerynditracker#49]
Install of scikit-surgerynditracker fails with the following message:
```
C:\Users\Local>pip install scikit-surgerynditracker
Defaulting to user installation because normal site-packages is not writeable
Collecting scikit-surgerynditracker
  Using cached scikit-surgerynditracker-0.2.1.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Collecting six>=1.10
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: numpy>=1.11 in c:\users\local\appdata\roaming\python\python39\site-packages (from scikit-surgerynditracker) (1.22.4)
Collecting ndicapi>=3.2.6
  Using cached ndicapi-3.2.8.tar.gz (32 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Local\AppData\Local\Temp\pip-install-ytdf643t\ndicapi_0636c52b4c3a430c9e835f75caecc029\setup.py", line 10, in <module>
          long_description = io.open('README.pypi.md', encoding="utf-8").read()
      FileNotFoundError: [Errno 2] No such file or directory: 'README.pypi.md'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: You are using pip version 22.0.4; however, version 22.1.1 is available.
You should consider upgrading via the 'C:\Program Files\Python39\python.exe -m pip install --upgrade pip' command.
```

**Comment by thompson318** [comment]
We use pre-built binaries for ndicapi [here](https://pypi.org/project/ndicapi/#files). This error usually happens when we don't have a pre built binary for your operating system. It looks like you're using python 39 on 64 bit windows. Is that right? If so I can try and set our [runners](https://github.com/SciKit-Surgery/ndicapi/actions/runs/1530639714) to build a binary for this. In the meantime you could try using python 38 which should work straight away.

**Comment by Mixmorks** [comment]
I was using python 39 on a 64 bit Windows. I have made the switch to python 38 and that works, python 37 works as well. Thanks!

**Comment by PavanMantripragada** [comment]
Hi,
I'm using Ubuntu 18.04.6 LTS with python 3.8.13 and I still get this msg when I run `pip3 install scikit-surgerynditracker`.

`Collecting scikit-surgerynditracker
  Using cached https://files.pythonhosted.org/packages/d0/39/4c87b26f06885fe26b637664fc77d4d0b05d8b86fd0c06de935cd99bad04/scikit-surgerynditracker-0.2.1.tar.gz
Collecting ndicapi>=3.2.6 (from scikit-surgerynditracker)
  Using cached https://files.pythonhosted.org/packages/43/b6/e43ddd691624b5c1cbcdf477d036846ea981a45b363d2bbf1bdd9dbc93b5/ndicapi-3.2.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0x7q1n00/ndicapi/setup.py", line 10, in <module>
        long_description = io.open('README.pypi.md', encoding="utf-8").read()
    FileNotFoundError: [Errno 2] No such file or directory: 'README.pypi.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0x7q1n00/ndicapi/`

**Comment by thompson318** [comment]
I'm not sure why but your pip is trying to build ndicapi from source ndicapi-3.2.8.tar.gz rather than downloading the pre-built binary. Can you please try running 'pip install --no-cache-dir ndicapi' and posting the output here. Like:
`pip install --no-cache-dir ndicapi
  
Collecting ndicapi
Downloading ndicapi-3.2.8-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (229 kB)
     |████████████████████████████████| 229 kB 722 kB/s            
Installing collected packages: ndicapi
Successfully installed ndicapi-3.2.8
`

**Comment by thompson318** [comment]
I think there are now prebuilt binaries for ndicapi on py39 so py36, py37, py38, and py39 should all be supported.

**Comment by thompson318** [comment]
Thanks for the further information. I'm not sure why it's doing that. All our prebuilt Linux binaries are 64 bit. Is your virtual machine 32 bit?

**Comment by thompson318** [comment]
Please can you try running "pip debug --verbose" and post the output here.
