### ISSUE TITLE
Improve Error Message when ROM file(s) does not exist

### ISSUE THREAD

**Issue by rajkundu** [SciKit-Surgery/scikit-surgerynditracker#51]
Hello! This is not really an issue and is more of a minor suggestion.

A few times when connecting to cameras, I've waited a few seconds (upwards of 10?) to initialize the camera before getting the following error message:
`OSError: POLARIS 0x13: Unable to initialize Tool-in-Port`.

In my case, this error was simply caused by me not realizing that I had run my script from the wrong working directory - so the `romfiles` paths which I passed to the `NDITracker` constructor did not exist when it came time to initialize them. Because of this, I'd like to propose a small addition to `nditracker.py`: before initializing the camera and all, first check to ensure that all of the passed `romfiles` actually exist, and throw an error/exception if they don't.

For example, I think it would make sense to add the following code to either the `NDITracker` constructor or `_check_config` functions (or wherever makes the most sense):
```python
for romfile in configuration.get("romfiles"):
    if not os.path.exists(romfile):
        raise FileNotFoundError(f"ROM file '{romfile}' does not exist.")
```
There is already this exact loop in each of the `_check_config` functions, so adding this functionality would be trivial. Also, the `os` module is already imported in `nditracker.py`, so this small addition wouldn't be adding much complexity. This is all just a thought, but hopefully a useful one! Thanks!

**Comment by thompson318** [comment]
Hello, yes that would be a good idea, thank you. There are three _check_config functions so it could be added to them all. I think the best way to this would be for you to contribute the code via a fork and pull request, that way you get to show up as a contributor. Can you fork the repository, add the change and then create a pull request?

**Comment by rajkundu** [comment]
Hi - I would be happy to! I was just a bit hesitant because I looked at the contributing guidelines and saw that testing is required, and I am not personally very familiar with testing (though I'm willing to learn!). As this is a rather small and targeted change to the code, perhaps it either doesn't need to be thoroughly tested in that way, or perhaps someone else could help me out with that part? In any case, thank you! I'll fork and submit a PR now.

**Comment by thompson318** [comment]
Thanks, please give it a try. If we're lucky continuous integration testing on github actions will work out of the box on your fork. If not I'm happy to help out.

**Comment by thompson318** [comment]
Thanks for the contribution. I had to sort a couple of tests but it was very quick.

**Comment by rajkundu** [comment]
Of course! Thank you!!
