### ISSUE TITLE
NDI connect Error code 259

### ISSUE THREAD

**Issue by HiunIce** [SciKit-Surgery/scikit-surgerynditracker#53]
Hi, 

I am using NDI POLARIS SPECTRA and  I can connect NDI with NDI Tool Tracker & Cpp codes.
But when I using the kit in python, it shows errors below. 

" Setting:
{'tracker type': 'polaris', 'romfiles': ['C:\\SpecialBuild\\PlusBuild-Openhaptics\\PlusLibData\\ConfigFiles\\NdiToolDefinitions\\P4_MagStylus.rom']}
"
"Bugs
**In _connect_polaris:
       _get_serial_port_name:**
print(serial_ports, len(serial_ports), ports_to_probe)
Result: [<serial.tools.list_ports_common.ListPortInfo object at 0x000001C2BE9C8DC0>] 1 20

print("Probing port: ", port_no, " got name: ", name, " Result: ", result,)
**Result: Probing port:  0  got name:  COM4  Result:  259**
"

Hope for your replying

Thanks! 
Best regards.

**Comment by thompson318** [comment]
Hello, the value of result is set by the call to ndicapy.ndiProbe(name). You're getting 259 (0x0103 in hexadecimal) which is defined here:
https://github.com/SciKit-Surgery/ndicapi/blob/2github-actions/ndicapi.h#L1978 as "#define NDI_TIMEOUT         0x0103  /*!<\brief Device took >5 secs to reply */".
Do you know if your Polaris is connected to COM4? Things to check: Is it turned on? Is it connected to another bit of software that might stop it connecting to ours? I hope that helps. Please let me know how you get on.

**Comment by HiunIce** [comment]
> 
The Com4 is connected as step 5.

After restart my computer, the procedure is as following: 

0. open the NDI console, hear beep beep noise.
1. run the unittest code which copied from the md file.
2. output matrix like [nan] * 16 without beep beep sounds.
3. run the script again, show the error code 259 as metioned above. With beep beep sounds.
4. run -> shows step 2 -> run ->shows the step 3.
5. Start official NDI Track.exe . Connet successfully. (with beep beep noise) and the transform matrix is ok.
6. goes back to step 4.
7. fails

I dont know if step 2 is successed? 
And Why Error code 259 & [nan] * 16 appears alternately?

Thanks!

**Comment by thompson318** [comment]
The output matrix will be [nan]*16 if the tool you're trying to track (as defined in the ROM file) isn't in view at the time when you run get_frame(). You could try putting get_frame() in a loop to make it easier to move the tool around to check. I think the 259 error is probably due to not disconnecting from the tracker after the last run, so we get a time out when we try and reconnect?

**Comment by HiunIce** [comment]
> 

I finally got its rule:
After a long period of time, I need to open ndi tracker.exe first and then close it, otherwise even if we get the matrix, it may be nan value ( doubtful, but occurs once in 4 times)

and
1. When the scripts is run for the first time, it must be error 259.
2. When you run the script again, it can get the correct matrix.
Strangely, the 12 must be alternate. 

I suspect that 5 seconds is not enough when steo 1, and success in step 2 because there are another 5 seconds.

The attachment are display results and the display results in ndi tracker application.

Anyway, thanks for your code and answer, I can already use NDI in python.

I will try to find the bug above  and report to you when I fix it later

Thanks!
![image](https://user-images.githubusercontent.com/36978849/174802822-38b21457-4b21-458c-a686-e26166cae484.png)

![image](https://user-images.githubusercontent.com/36978849/174802850-e45c2f61-0c47-431d-89f9-50f4fa0038de.png)

**Comment by HiunIce** [comment]
Dear thompson,  @thompson318 

I have been using this library fluently until I used the 【third tracker】, it throws the following error:

"""
utf-8' codec can't decode byte 0x83 in position 2: invalid start byte
"""

I think it is because the buffer of NDI is not set large enough. 

Is there any way to solve this problem?

Besides: I solved the bug mentioned last time in a weird way：
【Call the function _get_serial_port_name twice】
”“
        if result != ndicapy.NDI_OKAY:
            print('please restart again')
            return None # return None
            raise IOError( # the origin version

And when it calls:
          if name is None:
            print('ndi link again')
            name = _get_serial_port_name(configuration)
”“

**Comment by thompson318** [comment]
Hello, I don't think it will be a lack of buffer issue. The buffers are set here [https://github.com/PlusToolkit/ndicapi/blob/master/ndicapi.h#L154](https://github.com/PlusToolkit/ndicapi/blob/master/ndicapi.h#L154) and here [https://github.com/PlusToolkit/ndicapi/blob/master/ndicapi.h#L171](https://github.com/PlusToolkit/ndicapi/blob/master/ndicapi.h#L171) where NDI_MAX_HANDLES is 24, set here [https://github.com/PlusToolkit/ndicapi/blob/master/ndicapi.h#L57](https://github.com/PlusToolkit/ndicapi/blob/master/ndicapi.h#L57). So 3 tools should not be a problem. 
One thing you could try quickly to see if it makes any difference is to change whether you're using BX (binary) or TX (text) transforms. See _set_use_bx_transforms here [https://github.com/SciKit-Surgery/scikit-surgerynditracker/blob/master/sksurgerynditracker/nditracker.py#L149](https://github.com/SciKit-Surgery/scikit-surgerynditracker/blob/master/sksurgerynditracker/nditracker.py#L149l). If you add your firmware to the list at [https://github.com/SciKit-Surgery/scikit-surgerynditracker/blob/master/sksurgerynditracker/nditracker.py#L161](https://github.com/SciKit-Surgery/scikit-surgerynditracker/blob/master/sksurgerynditracker/nditracker.py#L161) it might change the behavior, or at least result in some helpful debugging information.

**Comment by HiunIce** [comment]
> Hello, I don't think it will be a lack of buffer issue. The buffers are set here https://github.com/PlusToolkit/ndicapi/blob/master/ndicapi.h#L154 and here https://github.com/PlusToolkit/ndicapi/blob/master/ndicapi.h#L171 where NDI_MAX_HANDLES is 24, set here https://github.com/PlusToolkit/ndicapi/blob/master/ndicapi.h#L57. So 3 tools should not be a problem. One thing you could try quickly to see if it makes any difference is to change whether you're using BX (binary) or TX (text) transforms. See _set_use_bx_transforms here [https://github.com/SciKit-Surgery/scikit-surgerynditracker/blob/master/sksurgerynditracker/nditracker.py#L149](https://github.com/SciKit-Surgery/scikit-surgerynditracker/blob/master/sksurgerynditracker/nditracker.py#L149l). If you add your firmware to the list at https://github.com/SciKit-Surgery/scikit-surgerynditracker/blob/master/sksurgerynditracker/nditracker.py#L161 it might change the behavior, or at least result in some helpful debugging information.

When I change the BX to TX, it would not throw bugs, but fn, tracking, quality

**Comment by thompson318** [comment]
It looks like it's failing to track the third object. Have you checked that it can track that object on it's own (i.e. is the ROM file right for that object?). What happens if you change the order of the objects?

**Comment by HiunIce** [comment]
> It looks like it's failing to track the third object. Have you checked that it can track that object on it's own (i.e. is the ROM file right for that object?). What happens if you change the order of the objects?

I think the ROM file is ok because the trakcer.exe runs fluently.
And suppose there are A, B, C rom, each two has no problems,
In BX status:
1. A&B, A&C, B&C works, 
2. but once the third one (any rom in {A, B, C}) appears, the bug appears.

In TX status: 
1. works 
2. but data is nan, and 【qtransform == "MISSING"】
    A: 0, nan*16, nan
    B: 0, nan*16, nan
    C: 0, nan*16, nan

Thanks

**Comment by thompson318** [comment]
That's great, thank you. Can I just confirm that it tracks all 3 objects when set to use TX, but not when set to BX? If so I will update the code to include "Polaris Spectra Rev 006".

**Comment by HiunIce** [comment]
Yes, 3 objects work on TX but not on BX
