### ISSUE TITLE
Visualizing a point cloud as the probe is being tracked

### ISSUE THREAD

**Issue by ckolluru** [SciKit-Surgery/scikit-surgerynditracker#57]
Hi,

Are there examples of other projects that use this library to visualize the 3D point cloud as the tracking info is collected from the NDI camera? Additionally, having an option to interactively edit the point cloud (deleting noisy areas) and saving final data to a file would be a plus.

Thanks,
Chaitanya

**Comment by thompson318** [comment]
Thanks for your question. There's https://github.com/SciKit-Surgery/scikit-surgerytrackervisualisation which adds a live visualisation of the tracker position. It doesn't have any point cloud grabbing though. For visualising point clouds it would probably be easiest to do something with matplotlib. I wouldn't want to add that to SciKit-Surgerynditracker though as we're trying to keep the libraries as small as possible, to enable people to build them into their own applications.
SciKit-Surgerynditracker just does the hardware interface and gets the tracking data. Visualisation and editing would be done with separate packages, but you could combine them to make your own application.

**Comment by ckolluru** [comment]
Thank you for the explanation, appreciate it.
