### ISSUE TITLE
Support for NDI Optotrak Certus 

### ISSUE THREAD

**Issue by jsbyysheng** [SciKit-Surgery/scikit-surgerynditracker#66]
I wonder if this package will support NDI Optotrak Certus?

**Comment by thompson318** [comment]
I don't think so, sorry. I haven't used a Certus for several years but I think it's an entirely different interface to NDI's newer trackers (Polaris/Aurora). Have you tried?

**Comment by jsbyysheng** [comment]
Yeah, I have tried and it does not support Optotrak.
