### ISSUE TITLE
Quaternion format incorrectly specified

### ISSUE THREAD

**Issue by marcinbalicki** [SciKit-Surgery/scikit-surgerynditracker#69]
I have vega and it is returning quaternion as first 4 values and then 3 values for pos, while the documentation states the opposite. 
location:
https://github.com/SciKit-Surgery/scikit-surgerynditracker/blob/7dbba46f0d16ecf597e4f03c95b611c478629878/sksurgerynditracker/nditracker.py#L431

**Comment by thompson318** [comment]
@marcinbalicki, thanks for raising. I think it is fixed now. Can you please confirm and close if OK?
