### ISSUE TITLE
Visualize camera's output of NDI Vega VT

### ISSUE THREAD

**Issue by GRicciardi00** [SciKit-Surgery/scikit-surgerynditracker#83]
Hello,
I correctly managed to setup the tracker for the NDI Vega VT thanks to your library and the maintainers.
I would like to visualize the RGB camera of the device in my application but I don't know how do that.

**Comment by GRicciardi00** [comment]
Problem solved by opening a rstp connection to the device with OpenCV!

**Comment by thompson318** [comment]
@GRicciardi00 thanks for raising and resolving, sorry you got no response here, we were all on leave. I'm impressed that you got the RGB feed via OpenCV, I had no idea that could be done. I've only ever done it using NDI's own software.

**Comment by GRicciardi00** [comment]
> @GRicciardi00 thanks for raising and resolving, sorry you got no response here, we were all on leave. I'm impressed that you got the RGB feed via OpenCV, I had no idea that could be done. I've only ever done it using NDI's own software.
The problem is that there is latency between rgb and tracker feeds, this is because to get a good RGB stream I should open the connection through Gstreamer. Is it possible to do it by using OpenCV but I'm really struggling to solve this.

**Comment by GRicciardi00** [comment]
Exactly, the main problem was to find a way to install opencv with gstreamer support in windows. I tried several times to do it with CMake but always got problems, then I tried conda but didn't worked. For the moment I switched to linux with wsl and I think I'm near to fix the problem.
